### ISSUE TITLE
Failed to validate Rasa Pro license

### ISSUE THREAD

**Issue by nicoManthey** [RasaHQ/rasa-calm-demo#10]
Dear rasa team, 

I was trying to run the rasa-calm-demo. I use a rasa pro developer edition license key where it says: 

RASA_PRO_LICENSE=<your rasa pro license key>
OPENAI_API_KEY=<your openai api key>
RASA_DUCKLING_HTTP_URL=<url to the duckling server>

When I ran `make train` afterwards, I get the error:

2024-02-23 16:48:09 ERROR    rasa_plus.utils.licensing  - Could not decode license as JWT.
Failed to validate Rasa Pro license which was read from environmental variable `RASA_PRO_LICENSE`. Please ensure `RASA_PRO_LICENSE` is set to a valid license string.

My question is: 
Does the rasa pro developer edition license key not suffice in this example and the beheviour is as expected? 
Or is this unexpected behaviour, in which case I would be grateful for help and hints.

**Comment by varunshankar** [comment]
Hi @nicoManthey,

The Rasa Pro Developer Edition license key is sufficient to run the `rasa-calm-demo` bot. Please verify the license key set to `RASA_PRO_LICENSE`, as I suspect there may be an incorrect assignment of the key.

Please reach out if you have further questions. Thanks
