### ISSUE TITLE
Question: external triggers

### ISSUE THREAD

**Issue by fprojetto** [RasaHQ/rasa-calm-demo#14]
https://github.com/RasaHQ/rasa-calm-demo/blame/1435f9f8e7d9aac1ea08ab81a4cd3207b2e8a94e/data/flows/health_advice.yml#L3-L9

Would it be possible to trigger this flow externally through the API endpoint?

`
curl -H "Content-Type: application/json" -X POST -d \
'{"name": "health_advice"}' \
"http://localhost:5005/conversations/<conversation_id>/trigger_intent"
`

**Comment by fprojetto** [comment]
I’ve created a repo to showcase what I am trying to achieve. https://github.com/fprojetto/rasa-calm-external-triggers?tab=readme-ov-file

**Comment by varunshankar** [comment]
Currently, it is not possible to trigger a flow through an API endpoint. The dispatcher.utter_message method generates a bot response that is sent back to the user.

In the example you provided, you can trigger this flow using /health_advice. However, this cannot be done through an API endpoint.
