### ISSUE TITLE
Keep gettig langchain API connectionError retries

### ISSUE THREAD

**Issue by DavidCurryHan** [RasaHQ/rasa-calm-demo#51]
![image](https://github.com/user-attachments/assets/30ad288c-bcea-42af-9a04-43f757bf95f4)
as shown in the image
I have followed the instruction and successfully train the rasa model and actived the GUI interface. 
However as long as i type anything, the CALM-demo keep giving me this openai APIconnectionError shown in yellow.
Since I have successfully train the model, the program should have accessed the openai with no problem, it should not be a API key problem.
Also, I have write my own script of "OPENAI.chat.completions.create" which also works fine with the openai library version above 1.0.0.(since this rasa framework is using openai version 0.28.1)
I have installed the openai back to 0.28.1 and tried to set the timeout to 100seconds. I have also tried to set my proxy port to localhost:7890 and OPENAI_API_BASE to "https://openai.wndbac.cn/v1".
Eventually, the error stays.
Im not sure if its an openai problem (since the model training worked at 0.28.1 and script worked at 1.0.0) or its a problem from the rasa end.
Can anyone help? thankyou!

**Comment by maksim-m** [comment]
Hi @DavidCurryHan,

Based on the info provided, this seems like a network connectivity or proxy issue. During training, Rasa uses only the embeddings API, not the completions API, which might be blocked.
Starting with Rasa Pro 3.10, CALM uses [LiteLLM](https://litellm.vercel.app/) instead of LangChain and an updated OpenAI library. I recommend trying the latest version to see if this resolves the issue.

**Comment by DavidCurryHan** [comment]
> Hi @DavidCurryHan,
> 
> Based on the info provided, this seems like a network connectivity or proxy issue. During training, Rasa uses only the embeddings API, not the completions API, which might be blocked. Starting with Rasa Pro 3.10, CALM uses [LiteLLM](https://litellm.vercel.app/) instead of LangChain and an updated OpenAI library. I recommend trying the latest version to see if this resolves the issue.

Thank you for your reply!
